[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build =  'make'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'sbdchd/neoformat'

[[plugins]]
repo = 'vim-scripts/gtags.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-pathogen'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'vim-vdebug/vdebug'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'rizzatti/dash.vim'

[[plugins]]
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'Rykka/clickable.vim'

[[plugins]]
repo = 'Rykka/riv.vim'

[[plugins]]
repo = 'Shougo/echodoc.vim'

