# Ruby
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'haml', 'slim']
hook_add = '''
let g:rails_projections = {
      \ "app/view_objects/*.rb": {
      \   "command": "view_object",
      \   "test": [
      \     "spec/view_objects/{}_spec.rb"
      \   ]
      \ },
      \ "app/parameters/*_parameter.rb": {
      \   "command": "parameter"
      \ },
      \ "app/policies/*_policy.rb": {
      \   "command": "policy"
      \ },
      \ "app/queries/*_query.rb": {
      \   "command": "query"
      \ },
      \ "app/repositories/*_repository.rb": {
      \   "command": "repository"
      \ },
      \ "app/serializers/*_serializer.rb": {
      \   "command": "serializer"
      \ },
      \ "app/services/*_service.rb": {
      \   "command": "service"
      \ },
      \ "app/validators/*_validator.rb": {
      \   "command": "validator"
      \ },
      \ "app/values/*.rb": {
      \   "command": "value"
      \ },
      \ "app/filters/*_filter.rb": {
      \   "command": "filter"
      \ },
      \ "app/factories/*_factory.rb": {
      \   "command": "factory"
      \ },
      \ "app/decorators/*_decorator.rb": {
      \   "command": "decorator"
      \ },
      \ "app/cells/*_cell.rb": {
      \   "command": "cell"
      \ },
      \ "app/adapters/*_adapter.rb": {
      \   "command": "adapter"
      \ }}
'''

[[plugins]]
repo = '5t111111/denite-rails'
on_ft = ['ruby', 'haml', 'slim']

[[plugins]]
repo = 'tpope/vim-bundler'
on_ft = ['ruby', 'haml', 'slim']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby', 'haml', 'slim']

[[plugins]]
repo = 'ecomba/vim-ruby-refactoring'
on_ft = ['ruby', 'haml', 'slim']

# Python
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft= ['python', 'jinja']

[[plugins]]
repo = 'tweekmonster/django-plus.vim'
on_ft= ['python', 'jinja']

[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'
on_ft= ['python', 'jinja']

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft= ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft= ['python']

# Golang
[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']

[[plugins]]
repo = 'jodosha/vim-godebug'
on_ft = ['go']

# Rust
[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = ['rust']
hook_post_source = '''
let g:deoplete#sources#rust#racer_binary=(system('which racer'))
let g:deoplete#sources#rust#rust_source_path=(system('rustc --print sysroot').'/lib/rustlib/src/rust/src')
let g:deoplete#sources#rust#show_duplicates = 1
let g:deoplete#sources#rust#disable_keymap = 1
let g:deoplete#sources#rust#documentation_max_height = 20
'''

# JavaScript
[[plugins]]
repo ='carlitux/deoplete-ternjs'
build = 'npm install -g tern'

on_ft = ['javascript', 'javascript.jsx']

# OCaml
[[plugins]]
repo = 'def-lkb/ocp-indent-vim'
on_ft = ['ocaml']

[[plugins]]
repo = 'copy/deoplete-ocaml'
on_ft = ['ocaml']

# VimScript
[[plugins]]
repo = 'junegunn/vader.vim'
on_ft = ['vim']

[[plugins]]
repo = 'vim-jp/vital.vim'
on_ft = ['vim']

# Terraform
[[plugins]]
repo = 'juliosueiras/vim-terraform-completion'
on_ft = ['terraform']

# Productivity

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = ['toml', 'vim', 'yaml', 'markdown']
